#!/usr/bin/env python3
"""Regenerates sw.js with a fresh precache file list and a new cache version.
Run this any time files are added/changed (new advisor text, new photos, etc.)
before deploying, so phones that already installed the site pick up the update
and re-cache the new files for offline use.
"""
import os
import time

ROOT = os.path.dirname(os.path.abspath(__file__))

EXTS = (".html", ".css", ".js", ".json", ".svg", ".png", ".jpg", ".jpeg", ".mp4")
SKIP_DIRS = {".git", "node_modules"}

files = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
    for fn in filenames:
        if fn == "sw.js":
            continue
        if fn.lower().endswith(EXTS):
            rel = os.path.relpath(os.path.join(dirpath, fn), ROOT)
            files.append("./" + rel.replace(os.sep, "/"))

files.sort()
version = str(int(time.time()))

precache_list = ",\n  ".join(f'"{f}"' for f in files)

sw_content = f"""// Auto-generated by build-sw.py — do not edit by hand.
const CACHE_VERSION = "{version}";
const CACHE_NAME = "koubou-archive-" + CACHE_VERSION;

const PRECACHE_URLS = [
  {precache_list}
];

self.addEventListener("install", (event) => {{
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  const req = event.request;
  if (req.method !== "GET") return;

  event.respondWith(
    caches.match(req).then((cached) => {{
      if (cached) return cached;
      return fetch(req)
        .then((res) => {{
          if (res && res.ok) {{
            const resClone = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(req, resClone));
          }}
          return res;
        }})
        .catch(() => {{
          if (req.mode === "navigate") {{
            return caches.match("./index.html");
          }}
        }});
    }})
  );
}});
"""

with open(os.path.join(ROOT, "sw.js"), "w", encoding="utf-8") as f:
    f.write(sw_content)

print(f"sw.js regenerated: version={version}, {len(files)} files precached")
