// Auto-generated by build-sw.py — do not edit by hand.
const CACHE_VERSION = "1783298654";
const CACHE_NAME = "koubou-archive-" + CACHE_VERSION;

const PRECACHE_URLS = [
  "./.claude/launch.json",
  "./css/style.css",
  "./data/advisors.json",
  "./data/data.js",
  "./data/qa.json",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-32.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./images/placeholder-apart.svg",
  "./images/placeholder-container.svg",
  "./images/placeholder-default.svg",
  "./images/placeholder-hanare.svg",
  "./images/placeholder-jitaku.svg",
  "./images/placeholder-kominka.svg",
  "./images/placeholder-nakako.svg",
  "./images/placeholder-niwa.svg",
  "./index.html",
  "./js/main.js",
  "./manifest.json",
  "./media/amino/photo1.jpg",
  "./media/amino/photo2.jpg",
  "./media/amino/photo3.jpg",
  "./media/amino/photo4.jpg",
  "./media/amino/photo5.jpg",
  "./media/amino/video1.mp4",
  "./media/ayano/photo1.jpg",
  "./media/ayano/photo2.jpg",
  "./media/ayano/photo3.jpg",
  "./media/ayano/photo4.jpg",
  "./media/ayano/photo5.jpg",
  "./media/ayano/photo6.jpg",
  "./media/ayano/photo7.jpg",
  "./media/ayano/photo8.jpg",
  "./media/ayano/photo9.jpg",
  "./media/ayano/video1.mp4",
  "./media/ayano/video2.mp4",
  "./media/ayano/video3.mp4",
  "./media/nakada/photo1.jpg",
  "./media/nakada/photo2.jpg",
  "./media/nakada/photo3.jpg",
  "./media/nakada/photo4.jpg",
  "./media/nakada/photo5.jpg",
  "./media/nakada/photo6.jpg",
  "./media/nobue/photo1.jpg",
  "./media/nobue/photo2.jpg",
  "./media/nobue/photo3.jpg",
  "./media/nobue/photo4.jpg",
  "./media/nobue/photo5.jpg",
  "./media/nobue/video1.mp4",
  "./media/nobue/video2.mp4",
  "./media/satomi/photo1.jpg",
  "./media/satomi/photo2.jpg",
  "./media/satomi/photo3.jpg",
  "./media/satomi/photo4.jpg",
  "./media/satomi/photo5.jpg",
  "./media/satomi/photo6.jpg",
  "./media/satomi/photo7.jpg",
  "./media/satomi/photo8.jpg",
  "./media/takako/photo1.jpg",
  "./media/takako/photo2.jpg",
  "./media/takako/video1.mp4",
  "./media/takasaki/photo1.jpg",
  "./media/takasaki/photo10.jpg",
  "./media/takasaki/photo11.jpg",
  "./media/takasaki/photo2.jpg",
  "./media/takasaki/photo3.jpg",
  "./media/takasaki/photo4.jpg",
  "./media/takasaki/photo5.jpg",
  "./media/takasaki/photo6.jpg",
  "./media/takasaki/photo7.jpg",
  "./media/takasaki/photo8.jpg",
  "./media/takasaki/photo9.jpg",
  "./media/terumi/photo1.jpg",
  "./media/terumi/photo10.jpg",
  "./media/terumi/photo11.jpg",
  "./media/terumi/photo12.jpg",
  "./media/terumi/photo13.jpg",
  "./media/terumi/photo2.jpg",
  "./media/terumi/photo3.jpg",
  "./media/terumi/photo4.jpg",
  "./media/terumi/photo5.jpg",
  "./media/terumi/photo6.jpg",
  "./media/terumi/photo7.jpg",
  "./media/terumi/photo8.jpg",
  "./media/terumi/photo9.jpg",
  "./media/terumi/video1.mp4",
  "./media/tomita/photo1.jpg",
  "./media/tomita/photo2.jpg",
  "./media/tomita/photo3.jpg",
  "./media/tomita/photo4.jpg",
  "./media/tomita/photo5.jpg",
  "./media/tomita/photo6.jpg",
  "./media/tomita/photo7.jpg"
];

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  // Network-first: always try to get the latest version from the internet.
  // Only use the saved offline copy if there is no connection right now.
  event.respondWith(
    fetch(req)
      .then((res) => {
        if (res && res.ok) {
          const resClone = res.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(req, resClone));
        }
        return res;
      })
      .catch(() => {
        return caches.match(req).then((cached) => {
          if (cached) return cached;
          if (req.mode === "navigate") {
            return caches.match("./index.html");
          }
        });
      })
  );
});
